INSERT INTO GENRE (ID, NAME)
SELECT 1, 'Комедия' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 1)
UNION ALL
SELECT 2, 'Драма' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 2)
UNION ALL
SELECT 3, 'Мультфильм' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 3)
UNION ALL
SELECT 4, 'Триллер' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 4)
UNION ALL
SELECT 5, 'Документальный' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 5)
UNION ALL
SELECT 6, 'Боевик' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM GENRE WHERE ID = 6);

INSERT INTO RATING (ID, NAME)
SELECT 1, 'G' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RATING WHERE ID = 1)
UNION ALL
SELECT 2, 'PG' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RATING WHERE ID = 2)
UNION ALL
SELECT 3, 'PG-13' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RATING WHERE ID = 3)
UNION ALL
SELECT 4, 'R' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RATING WHERE ID = 4)
UNION ALL
SELECT 5, 'NC-17' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM RATING WHERE ID = 5);